# Generated by Django 2.2.6 on 2020-02-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GovtJobApp', '0003_auto_20200227_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='railwayjobsmodel',
            name='post_name',
            field=models.CharField(max_length=300),
        ),
    ]
