# Generated by Django 2.2.6 on 2020-02-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GovtJobApp', '0004_auto_20200227_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestNotificationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.CharField(max_length=100)),
                ('recuritment_board', models.CharField(max_length=100)),
                ('post_name', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('advt_no', models.CharField(max_length=100)),
                ('last_date', models.CharField(max_length=100)),
            ],
        ),
    ]
