# Generated by Django 2.2.6 on 2020-02-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GovtJobApp', '0005_latestnotificationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestnotificationmodel',
            name='post_date',
            field=models.CharField(max_length=300),
        ),
    ]
