# Generated by Django 2.2.6 on 2020-02-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GovtJobApp', '0006_auto_20200228_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('post_name', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('advt_no', models.CharField(max_length=100)),
                ('last_date', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='LatestNotificationModel',
        ),
    ]
