# Generated by Django 2.2.6 on 2020-02-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GovtJobApp', '0007_auto_20200228_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankmodel',
            name='bank_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bankmodel',
            name='post_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='bankmodel',
            name='qualification',
            field=models.CharField(max_length=200),
        ),
    ]
