# Generated by Django 2.2.6 on 2020-02-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GovtJobApp', '0008_auto_20200228_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiharModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.CharField(max_length=100)),
                ('recruitment_board', models.CharField(max_length=200)),
                ('post_name', models.CharField(max_length=300)),
                ('qualification', models.CharField(max_length=200)),
                ('advt_no', models.CharField(max_length=100)),
                ('last_date', models.CharField(max_length=100)),
            ],
        ),
    ]
