# Generated by Django 2.2.6 on 2020-02-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GovtJobApp', '0009_biharmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankmodel',
            name='advt_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bankmodel',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='bankmodel',
            name='last_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bankmodel',
            name='post_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bankmodel',
            name='post_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='bankmodel',
            name='qualification',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='biharmodel',
            name='advt_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='biharmodel',
            name='last_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='biharmodel',
            name='post_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='biharmodel',
            name='post_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='biharmodel',
            name='qualification',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='biharmodel',
            name='recruitment_board',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='railwayjobsmodel',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='railwayjobsmodel',
            name='education',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='railwayjobsmodel',
            name='last_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='railwayjobsmodel',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='railwayjobsmodel',
            name='post_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='railwayjobsmodel',
            name='total_post',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
